ktor:
    application:
        modules:
            - com.eynnzerr.ApplicationKt.module
    deployment:
        port: 18080

storage:
    migrationLocation: "classpath:db/migration"
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://db:5432/bandoriscription"
    user: "changeme" # Environment variable override: DB_USER
    password: "changeme" # Environment variable override: DB_PASSWORD
    maximumPoolSize: 10

bandoristation:
    externalApiUrl: "https://server.bandoristation.com"

cleanup:
  retention_days: 1
  interval_hours: 24

jwt:
    # Environment variable override: JWT_SECRET
    issuer: "bandoriscription"
    audience: "bandoristation_mobile"
    realm: "Access to bandoriscription"

cors:
  allowedHosts:
    - "localhost:8080"
    - "eynnzerr.top"
